name: docss
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  flutter_gen: any
  equatable: ^2.0.5
  get_it: ^7.6.7
  floor: ^1.4.2
  flutter_hooks: ^0.21.0
  retrofit: ^4.1.0
  dio: ^5.4.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.1.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

assets:
  - .env

flutter:
  uses-material-design: true
  generate: true
